name: flutter_ping_wire
description: "With FlutterPing, you can serve different parts of your application via various APIs, enabling you to craft sophisticated micro mobile apps."
version: 0.1.1
homepage: "https://docs.flutterping.com"
repository: "https://github.com/yahya077/flutterping"
issue_tracker: "https://roadmap.flutterping.com/projects/bugs"
documentation: "https://docs.flutterping.com"
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'The screenshot illustrates the structure and content of a proper FlutterPing response.'
    path: doc/screenshots/dummy_response.png

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: