clients:
  default:
    name: default
    description: Default API Client
    url: https://example.com/api
    headers:
      Content-Type: application/json
      Accept: application/json

loaders:
  app:
    client: "default"
    endpoint: "/route/runApp"
    method: "GET"

default_client: "default"
