clients:
  first_client:
    description: "This is simple client"
    url: "https://b2de8312-cf06-40dd-81f6-116b761b66eb.mock.pstmn.io"
    headers:
      Authorization: "Bearer token"
loaders:
  simple:
    client: "first_client"
    endpoint: "/simple"
    method: "GET"
  router:
    client: "first_client"
    endpoint: "/router"
    method: "GET"
  forExistingProject:
    client: "first_client"
    endpoint: "/forExistingProject"
    method: "GET"